### ISSUE TITLE
tls: flaky TestInvalidCerts

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1529]
```
      --- FAIL: TestInvalidCerts/client_offending:_signature_is_invalid (0.03s)
  panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  	panic: runtime error: invalid memory address or nil pointer dereference
  [signal 0xc0000005 code=0x0 addr=0x10 pc=0xeae8a3]
  
  goroutine 144 [running]:
  testing.tRunner.func1.2({0xeea760, 0x12c5398})
  	C:/hostedtoolcache/windows/go/1.17.10/x64/src/testing/testing.go:1209 +0x2ab
  testing.tRunner.func1(0x118843c0)
  	C:/hostedtoolcache/windows/go/1.17.10/x64/src/testing/testing.go:1212 +0x27d
  panic({0xeea760, 0x12c5398})
  	C:/hostedtoolcache/windows/go/1.17.10/x64/src/runtime/panic.go:1038 +0x1bc
  github.com/libp2p/go-libp2p/p2p/security/tls.TestInvalidCerts.func19(0x118843c0)
  	D:/a/go-libp2p/go-libp2p/p2p/security/tls/transport_test.go:494 +0x4f3
  testing.tRunner(0x118843c0, 0x11b4aa50)
  	C:/hostedtoolcache/windows/go/1.17.10/x64/src/testing/testing.go:1259 +0xe6
  created by testing.(*T).Run
  	C:/hostedtoolcache/windows/go/1.17.10/x64/src/testing/testing.go:1306 +0x33a

**Comment by marten-seemann** [comment]
This only fails on Windows, but with different error messages:

```
=== RUN   TestInvalidCerts/server_offending:_signature_is_malformed
    transport_test.go:60:
                Error Trace:    transport_test.go:60
                                                        transport_test.go:512
                Error:          Received unexpected error:
                                dial tcp 127.0.0.1:49534: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
                Test:           TestInvalidCerts/server_offending:_signature_is_malformed
--- FAIL: TestInvalidCerts (0.03s)
```

```
=== RUN   TestInvalidCerts/client_offending:_signature_is_invalid
    transport_test.go:490: unexpected error: read tcp 127.0.0.1:64919->127.0.0.1:64916: wsarecv: An existing connection was forcibly closed by the remote host.
--- FAIL: TestInvalidCerts (0.03s)
```

```
=== RUN   TestInvalidCerts/client_offending:_signature_is_invalid
    transport_test.go:60:
                Error Trace:    transport_test.go:60
                                                        transport_test.go:470
                Error:          Received unexpected error:
                                dial tcp 127.0.0.1:49509: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
                Test:           TestInvalidCerts/client_offending:_signature_is_invalid
    transport_test.go:56:
                Error Trace:    transport_test.go:56
                                                        asm_arm64.s:1133
                Error:          Received unexpected error:
                                accept tcp 127.0.0.1:49509: use of closed network connection
                Test:           TestInvalidCerts/client_offending:_signature_is_invalid
--- FAIL: TestInvalidCerts (0.03s)
```

**Comment by marten-seemann** [comment]
This is very frustrating. Windows doesn't allow us to reliably dial a TCP connection. A damn TCP connection!!
