### ISSUE TITLE
CI Flakiness around `TestQUICAndWebTransport`

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p#1922]
https://github.com/libp2p/go-libp2p/actions/runs/3570089347/jobs/6000726079

This times out while waiting to close the host.

**Comment by marten-seemann** [comment]
Another failure in https://github.com/libp2p/go-libp2p/actions/runs/4121012639/jobs/7116306268

The interesting Go routine is this one:
```
 goroutine 290 [select, 9 minutes]:
  github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).dialPeer(0xc000160f00, {0x1a78d30, 0xc00004a128}, {0xc001046a50, 0x26})
  	/home/runner/work/go-libp2p/go-libp2p/p2p/host/basic/basic_host.go:726 +0x28b
  github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).Connect(0xc000160f00, {0x1a78d30, 0xc00004a128}, {{0xc001046a50, 0x26}, {0xc000eff9c0, 0x3, 0x4}})
  	/home/runner/work/go-libp2p/go-libp2p/p2p/host/basic/basic_host.go:709 +0x1f8
  github.com/libp2p/go-libp2p/p2p/test/quic_test.TestQUICAndWebTransport(0xc000e8b040)
  	/home/runner/work/go-libp2p/go-libp2p/p2p/test/quic/quic_test.go:151 +0x7f9
  testing.tRunner(0xc000e8b040, 0x1853778)
  	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x217
  created by testing.(*T).Run
  	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x75e
```

The timeout happens when waiting for `IdentifyWait`: https://github.com/libp2p/go-libp2p/blob/635cc650cfb3bbbdb4bef6ae29f45e3c8966fb31/p2p/host/basic/basic_host.go#L726-L730

**Comment by MarcoPolo** [comment]
Hasn't happened lately
