### ISSUE TITLE
Metrics shouldn't slow us down

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#235]
We're seeing some pretty severe lock contention (mostly because we record every message sent...).

E.g.,

```
goroutine 414225723 [0s]:
sync.runtime_SemacquireMutex [0xc4201c8604, 0xd6990624d192e800]
	/usr/local/go/src/runtime/sema.go:71
sync.(*Mutex).Lock [0xc4201c8600]
	/usr/local/go/src/sync/mutex.go:134
sync.(*RWMutex).Lock [0xc4201c8600]
	/usr/local/go/src/sync/rwmutex.go:93
gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics.(*StandardMeter).Mark [0xc4201c8600, 0x25]
	/go/src/gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics/meter.go:152
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics.(*BandwidthCounter).LogSentMessage [0xc420182c00, 0x25]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/bw_stats.go:35
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics.(Reporter).LogSentMessage-fm [0x25]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/conn/conn.go:16
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/conn.(*MeteredConn).Write [0xc471d02640, 0xc42c3de6c0, 0x25, 0x40, 0x40, 0x0, 0x0]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/conn/conn.go:37
gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn.(*singleConn).Write [0xc46975d580, 0xc42c3de6c0, 0x25, 0x40, 0xc42c3de6c4, 0x21, 0x3c]
	/go/src/gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn/conn.go:131
gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio.(*etmWriter).WriteMsg [0xc43d70c160, 0xc4884a6ff0, 0x1, 0xa, 0x0, 0x0]
	/go/src/gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio/rw.go:72
gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio.(*etmWriter).Write [0xc43d70c160, 0xc4884a6ff0, 0x1, 0xa, 0xc468872d78, 0xdcac50, 0xc43d70c2b0]
	/go/src/gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio/rw.go:42
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*readWriter).Write [0xc434031da0, 0xc4884a6ff0, 0x1, 0xa, 0x2c, 0x3c, 0x40]
	<autogenerated>:1
gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn.(*secureConn).Write [0xc4276a1de0, 0xc4884a6ff0, 0x1, 0xa, 0x12a9b80, 0x1347840, 0x1]
	/go/src/gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn/secure_conn.go:120
bytes.(*Reader).WriteTo [0xc4a59ec210, 0x7f35f4d05fb8, 0xc4276a1de0, 0x7f35f0216310, 0xc4a59ec210, 0x17000000001]
	/usr/local/go/src/bytes/reader.go:134
io.copyBuffer [0x7f35f4d05fb8, 0xc4276a1de0, 0x1c3e460, 0xc4a59ec210, 0x0, 0x0, 0x0, 0x137f940, 0x0, 0x7f35f4d05fb8]
	/usr/local/go/src/io/io.go:382
io.Copy [0x7f35f4d05fb8, 0xc4276a1de0, 0x1c3e460, 0xc4a59ec210, 0xc4276a1de0, 0x0, 0x0]
	/usr/local/go/src/io/io.go:362
gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux.(*Session).send [0xc4258ea6e0]
	/go/src/gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux/session.go:387
created by gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux.newSession []
	/go/src/gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux/session.go:109

goroutine 458182691 [0s]:
sync.runtime_SemacquireMutex [0xc4201c8604, 0xd6990624d192e800]
	/usr/local/go/src/runtime/sema.go:71
sync.(*Mutex).Lock [0xc4201c8600]
	/usr/local/go/src/sync/mutex.go:134
sync.(*RWMutex).Lock [0xc4201c8600]
	/usr/local/go/src/sync/rwmutex.go:93
gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics.(*StandardMeter).Mark [0xc4201c8600, 0x25]
	/go/src/gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics/meter.go:152
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics.(*BandwidthCounter).LogSentMessage [0xc420182c00, 0x25]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/bw_stats.go:35
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics.(Reporter).LogSentMessage-fm [0x25]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/conn/conn.go:16
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/conn.(*MeteredConn).Write [0xc4511ebf60, 0xc4b4375100, 0x25, 0x40, 0x40, 0x0, 0x0]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/conn/conn.go:37
gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn.(*singleConn).Write [0xc452b1d9c0, 0xc4b4375100, 0x25, 0x40, 0xc4b4375104, 0x21, 0x3c]
	/go/src/gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn/conn.go:131
gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio.(*etmWriter).WriteMsg [0xc4258b3ce0, 0xc42e320160, 0x1, 0xa, 0x0, 0x0]
	/go/src/gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio/rw.go:72
gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio.(*etmWriter).Write [0xc4258b3ce0, 0xc42e320160, 0x1, 0xa, 0xc49a1f2d78, 0xdcac50, 0xc4258b3e30]
	/go/src/gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio/rw.go:42
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*readWriter).Write [0xc44d2c7da0, 0xc42e320160, 0x1, 0xa, 0x2c, 0x3c, 0x40]
	<autogenerated>:1
gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn.(*secureConn).Write [0xc44a2a16c0, 0xc42e320160, 0x1, 0xa, 0x12a9b80, 0x1347840, 0x1]
	/go/src/gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn/secure_conn.go:120
bytes.(*Reader).WriteTo [0xc48efab4d0, 0x7f35f4d05fb8, 0xc44a2a16c0, 0x7f35f0216310, 0xc48efab4d0, 0x17000000001]
	/usr/local/go/src/bytes/reader.go:134
io.copyBuffer [0x7f35f4d05fb8, 0xc44a2a16c0, 0x1c3e460, 0xc48efab4d0, 0x0, 0x0, 0x0, 0x137f940, 0x0, 0x7f35f4d05fb8]
	/usr/local/go/src/io/io.go:382
io.Copy [0x7f35f4d05fb8, 0xc44a2a16c0, 0x1c3e460, 0xc48efab4d0, 0xc44a2a16c0, 0x0, 0x0]
	/usr/local/go/src/io/io.go:362
gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux.(*Session).send [0xc4258eb4a0]
	/go/src/gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux/session.go:387
created by gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux.newSession []
	/go/src/gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux/session.go:109

goroutine 404223287 [0s]:
sync.runtime_SemacquireMutex [0xc4201c10ac, 0xc4a2391f00]
	/usr/local/go/src/runtime/sema.go:71
sync.(*Mutex).Lock [0xc4201c10a8]
	/usr/local/go/src/sync/mutex.go:134
gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics.(*StandardRegistry).GetOrRegister [0xc4201c10a0, 0xc4a2391f20, 0x2c, 0x12451a0, 0x1520548, 0x0, 0x0]
	/go/src/gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics/registry.go:80
gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics.GetOrRegisterMeter [0xc4a2391f20, 0x2c, 0x1c51240, 0xc4201c10a0, 0x22, 0xc4a2391f20]
	/go/src/gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics/meter.go:27
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics.(*BandwidthCounter).LogSentMessageStream [0xc420182c00, 0x30, 0x13c3268, 0x13, 0xc429947f50, 0x22]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/bw_stats.go:43
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics.(Reporter).LogSentMessageStream-fm [0x30, 0x13c3268, 0x13, 0xc429947f50, 0x22]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/stream/metered.go:33
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/stream.(*meteredStream).Write [0xc48d221500, 0xc427d8fec0, 0x30, 0x60, 0x1, 0x0, 0x0]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/stream/metered.go:49
gx/ipfs/QmTnsezaB1wWNRHeHnYrm8K4d5i9wtyj3GsqjC3Rt5b5v5/go-multistream.(*lazyConn).Write [0xc455204e00, 0xc427d8fec0, 0x30, 0x60, 0x1, 0x0, 0x0]
	/go/src/gx/ipfs/QmTnsezaB1wWNRHeHnYrm8K4d5i9wtyj3GsqjC3Rt5b5v5/go-multistream/lazy.go:124
gx/ipfs/QmRQ76P5dgvxTujhfPsCRAG83rC15jgb1G9bKLuomuC6dQ/go-libp2p/p2p/host/basic.(*streamWrapper).Write [0xc4453f0a40, 0xc427d8fec0, 0x30, 0x60, 0x1, 0x0, 0x0]
	/go/src/gx/ipfs/QmRQ76P5dgvxTujhfPsCRAG83rC15jgb1G9bKLuomuC6dQ/go-libp2p/p2p/host/basic/basic_host.go:559
gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io.(*varintWriter).WriteMsg [0xc4293a5000, 0x1c48360, 0xc43bb182d0, 0xc4269bcf30, 0xa]
	/go/src/gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io/varint.go:78
github.com/ipfs/go-ipfs/exchange/bitswap/message.(*impl).ToNetV1 [0xc449d652e0, 0x7f35f02167c8, 0xc4453f0a40, 0x7f35f02167c8, 0xc4453f0a40]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/message/message.go:229
github.com/ipfs/go-ipfs/exchange/bitswap/network.msgToStream [0x1c4b3a0, 0xc4201838c0, 0x1c51f80, 0xc4453f0a40, 0x1c53200, 0xc449d652e0, 0x0, 0xc4a1433fae]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/network/ipfs_impl.go:79
github.com/ipfs/go-ipfs/exchange/bitswap/network.(*streamMessageSender).SendMsg [0xc4d3633f90, 0x1c4b3a0, 0xc4201838c0, 0x1c53200, 0xc449d652e0, 0x0, 0xc4492c2780]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/network/ipfs_impl.go:64
github.com/ipfs/go-ipfs/exchange/bitswap.(*msgQueue).doWork [0xc45eae8540, 0x1c4b3a0, 0xc4201838c0]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:216
github.com/ipfs/go-ipfs/exchange/bitswap.(*msgQueue).runQueue [0xc45eae8540, 0x1c4b3a0, 0xc4201838c0]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:178
created by github.com/ipfs/go-ipfs/exchange/bitswap. [*WantManager).startPeerHandle]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:154

goroutine 537525914 [0s]:
sync.runtime_SemacquireMutex [0xc4201c10ac, 0xc4a920ae00]
	/usr/local/go/src/runtime/sema.go:71
sync.(*Mutex).Lock [0xc4201c10a8]
	/usr/local/go/src/sync/mutex.go:134
gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics.(*StandardRegistry).GetOrRegister [0xc4201c10a0, 0xc4a920ae80, 0x1e, 0x12451a0, 0x1520548, 0x0, 0x0]
	/go/src/gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics/registry.go:80
gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics.GetOrRegisterMeter [0xc4a920ae80, 0x1e, 0x1c51240, 0xc4201c10a0, 0x13, 0xc4a920ae80]
	/go/src/gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics/meter.go:27
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics.(*BandwidthCounter).LogSentMessageStream [0xc420182c00, 0x30, 0x13c3268, 0x13, 0xc47278d4a0, 0x22]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/bw_stats.go:46
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics.(Reporter).LogSentMessageStream-fm [0x30, 0x13c3268, 0x13, 0xc47278d4a0, 0x22]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/stream/metered.go:33
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/stream.(*meteredStream).Write [0xc473583740, 0xc42acbd9e0, 0x30, 0x60, 0x1, 0x0, 0x0]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/stream/metered.go:49
gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io.(*varintWriter).WriteMsg [0xc476dc8fc0, 0x1c48360, 0xc47dfb0410, 0xc442e29cf0, 0xa]
	/go/src/gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io/varint.go:78
github.com/ipfs/go-ipfs/exchange/bitswap/message.(*impl).ToNetV1 [0xc43aedcee0, 0x7f35f4cc4c10, 0xc473583740, 0x7f35f4cc4c10, 0xc473583740]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/message/message.go:229
github.com/ipfs/go-ipfs/exchange/bitswap/network.msgToStream [0x1c4b3a0, 0xc4201838c0, 0x1c51f00, 0xc473583740, 0x1c53200, 0xc43aedcee0, 0x0, 0xc4ad157fae]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/network/ipfs_impl.go:79
github.com/ipfs/go-ipfs/exchange/bitswap/network.(*streamMessageSender).SendMsg [0xc46c400210, 0x1c4b3a0, 0xc4201838c0, 0x1c53200, 0xc43aedcee0, 0x0, 0xc428180ae0]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/network/ipfs_impl.go:64
github.com/ipfs/go-ipfs/exchange/bitswap.(*msgQueue).doWork [0xc428bd8150, 0x1c4b3a0, 0xc4201838c0]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:216
github.com/ipfs/go-ipfs/exchange/bitswap.(*msgQueue).runQueue [0xc428bd8150, 0x1c4b3a0, 0xc4201838c0]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:178
created by github.com/ipfs/go-ipfs/exchange/bitswap. [*WantManager).startPeerHandle]
	/go/src/github.com/ipfs/go-ipfs/exchange/bitswap/wantmanager.go:154

goroutine 355132111 [0s]:
sync.runtime_SemacquireMutex [0xc4201c8604, 0xd6990624d192e800]
	/usr/local/go/src/runtime/sema.go:71
sync.(*Mutex).Lock [0xc4201c8600]
	/usr/local/go/src/sync/mutex.go:134
sync.(*RWMutex).Lock [0xc4201c8600]
	/usr/local/go/src/sync/rwmutex.go:93
gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics.(*StandardMeter).Mark [0xc4201c8600, 0x30]
	/go/src/gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics/meter.go:152
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics.(*BandwidthCounter).LogSentMessage [0xc420182c00, 0x30]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/bw_stats.go:35
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics.(Reporter).LogSentMessage-fm [0x30]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/conn/conn.go:16
gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/conn.(*MeteredConn).Write [0xc4255b37e0, 0xc4502bc9c0, 0x30, 0x40, 0x40, 0x0, 0x0]
	/go/src/gx/ipfs/QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14/go-libp2p-metrics/conn/conn.go:37
gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn.(*singleConn).Write [0xc47686ae00, 0xc4502bc9c0, 0x30, 0x40, 0xc4502bc9c4, 0x2c, 0x3c]
	/go/src/gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn/conn.go:131
gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio.(*etmWriter).WriteMsg [0xc4c061e2c0, 0xc44c738c40, 0xc, 0xc, 0x0, 0x0]
	/go/src/gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio/rw.go:72
gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio.(*etmWriter).Write [0xc4c061e2c0, 0xc44c738c40, 0xc, 0xc, 0xc49857c0c0, 0xc429baee38, 0x7f35f4d05f00]
	/go/src/gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio/rw.go:42
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*readWriter).Write [0xc4731dc320, 0xc44c738c40, 0xc, 0xc, 0x1, 0x0, 0x0]
	<autogenerated>:1
gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn.(*secureConn).Write [0xc477a51da0, 0xc44c738c40, 0xc, 0xc, 0x1, 0x0, 0x0]
	/go/src/gx/ipfs/QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i/go-libp2p-conn/secure_conn.go:120
gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux.(*Session).send [0xc464974c60]
	/go/src/gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux/session.go:374
created by gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux.newSession []
	/go/src/gx/ipfs/QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u/yamux/session.go:109
```

**Comment by Kubuxu** [comment]
As a note those are two different locks.

**Comment by Stebalien** [comment]
Will be fixed by using https://github.com/stebalien/go-flow-metrics
