### ISSUE TITLE
echo example with go1.9.2 darwin/amd64

### ISSUE THREAD

**Issue by lavalampmj** [libp2p/go-libp2p#273]
```sh
> ./echo -secio -l 10000
2018/02/14 19:41:48 I am /ip4/127.0.0.1/tcp/10000/ipfs/QmfLBgJniFEmmAgRd5a96WME4Dm1T76fkUnHfy1MCAsfPH
2018/02/14 19:41:48 Now run "./echo -l 10001 -d /ip4/127.0.0.1/tcp/10000/ipfs/QmfLBgJniFEmmAgRd5a96WME4Dm1T76fkUnHfy1MCAsfPH -secio" on a different terminal
2018/02/14 19:41:48 listening for connections
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x134bf5a]

goroutine 54 [running]:
gx/ipfs/QmSxBdRmouj5T3c8UV4Y1zvShCHe7APV9RU3tEn5voLQjb/go-peerstream.(*Swarm).NewStreamWithConn(0xc42009a180, 0xc42044a000, 0xc42022f700, 0x0, 0x6000000014bc77d)
	/Users/mauricejeffery/go/src/gx/ipfs/QmSxBdRmouj5T3c8UV4Y1zvShCHe7APV9RU3tEn5voLQjb/go-peerstream/swarm.go:328 +0xba
gx/ipfs/QmSxBdRmouj5T3c8UV4Y1zvShCHe7APV9RU3tEn5voLQjb/go-peerstream.(*Conn).NewStream(0xc42044a000, 0xc42022f5e8, 0x1029f59, 0xc400000008)
	/Users/mauricejeffery/go/src/gx/ipfs/QmSxBdRmouj5T3c8UV4Y1zvShCHe7APV9RU3tEn5voLQjb/go-peerstream/conn.go:143 +0x34
gx/ipfs/QmSD9fajyipwNQw3Hza2k2ifcBfbhGoC1ZHHgQBy4yqU8d/go-libp2p-swarm.(*Conn).NewSwarmStream(0xc42044a000, 0xc42022f5f8, 0xc42022f600, 0xc420080d00)
	/Users/mauricejeffery/go/src/gx/ipfs/QmSD9fajyipwNQw3Hza2k2ifcBfbhGoC1ZHHgQBy4yqU8d/go-libp2p-swarm/swarm_conn.go:79 +0x2b
gx/ipfs/QmSD9fajyipwNQw3Hza2k2ifcBfbhGoC1ZHHgQBy4yqU8d/go-libp2p-swarm.(*Conn).NewStream(0xc42044a000, 0x15fb9d8, 0xc420078d80, 0xc420080d88, 0xc42046ca00)
	/Users/mauricejeffery/go/src/gx/ipfs/QmSD9fajyipwNQw3Hza2k2ifcBfbhGoC1ZHHgQBy4yqU8d/go-libp2p-swarm/swarm_conn.go:85 +0x2b
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*IDService).IdentifyConn(0xc4200d45a0, 0x1827160, 0xc42044a000)
	/Users/mauricejeffery/go/src/github.com/libp2p/go-libp2p/p2p/protocol/identify/id.go:91 +0x29e
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newConnHandler(0xc42044a300, 0x1827160, 0xc42044a000)
	/Users/mauricejeffery/go/src/github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:227 +0xaf
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).(github.com/libp2p/go-libp2p/p2p/host/basic.newConnHandler)-fm(0x1827160, 0xc42044a000)
	/Users/mauricejeffery/go/src/github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:174 +0x3e
gx/ipfs/QmSD9fajyipwNQw3Hza2k2ifcBfbhGoC1ZHHgQBy4yqU8d/go-libp2p-swarm.(*Network).SetConnHandler.func1(0xc42044a000)
	/Users/mauricejeffery/go/src/gx/ipfs/QmSD9fajyipwNQw3Hza2k2ifcBfbhGoC1ZHHgQBy4yqU8d/go-libp2p-swarm/swarm_net.go:160 +0x3b
created by gx/ipfs/QmSD9fajyipwNQw3Hza2k2ifcBfbhGoC1ZHHgQBy4yqU8d/go-libp2p-swarm.(*Swarm).SetConnHandler.func2
	/Users/mauricejeffery/go/src/gx/ipfs/QmSD9fajyipwNQw3Hza2k2ifcBfbhGoC1ZHHgQBy4yqU8d/go-libp2p-swarm/swarm.go:260 +0x67
```

**Comment by Stebalien** [comment]
Looks like https://github.com/libp2p/go-libp2p/issues/263
